### ISSUE TITLE
Already a thing

### ISSUE THREAD

**Issue by qb42** [nielsbasjes/minecraft-open-to-lan#1]
There is a command in game to use a specific port (/publish 6666). I think it would be better to have a gui option in "Open to LAN" that remembers your choice but /publish works well enough and doesn't introduce any vulnerabilities.

https://minecraft.gamepedia.com/Commands/publish

PS. Sorry, this really should be a comment on your SE post but I don't have any reputation.

**Comment by nielsbasjes** [comment]
Thanks for the heads up. I'm going to document this.

**Comment by nielsbasjes** [comment]
Done.
I've updated the readme here and my answer here
https://gaming.stackexchange.com/a/372500/26776
